=== DanieleSignoroni/ValvorobicaW/4.7/src/it/valvorobica/thip/logis/rf/xml/lg.dtd
<!ENTITY versione "1.0">
<!ELEMENT LogisLogin (form+)>
<!ELEMENT form (field*, list*, printer*, hotkeys*)>
<!ATTLIST form
      Name CDATA #REQUIRED
      Beep (alert|warning|hello|none) "none"
      Type (normal|popup) "normal"
      Acknowledge (byFKey|lastField) "lastField"
>
<!ELEMENT field (type)>
<!ATTLIST field
      Name CDATA #REQUIRED
      SourceType (keyboard|all|scanner) "all"
      AcceptValueMode (auto|enter) "enter"
      Mandatory (true|false) "false"
      Value CDATA #IMPLIED
      Visible (true|false) "true"
      Row CDATA #REQUIRED
      Column CDATA #REQUIRED
      Height CDATA #REQUIRED
      Width CDATA #REQUIRED
      Sequence CDATA #REQUIRED
>
<!ELEMENT type (#PCDATA)>
<!ATTLIST type 
      Size CDATA #REQUIRED
      Scale CDATA #REQUIRED
      Display (input|output) "output"
      Justify (left|right) "left"
>
<!ELEMENT list (item+)>
<!ATTLIST list
      Name CDATA #REQUIRED
      Header (true|false) "true"
      Visible (true|false) "true"
      Row CDATA #REQUIRED
      Column CDATA #REQUIRED
      Height CDATA #IMPLIED
      Width CDATA #REQUIRED
      Check (none|single|multiple) "none"
>
<!ELEMENT item (#PCDATA)>
<!ELEMENT printer (printerline+)>
<!ATTLIST printer
      Name CDATA #REQUIRED
      LineSeparator (CR|LF|CRLF|LFCR) #REQUIRED
>
<!ELEMENT printerline (#PCDATA)>
<!ELEMENT hotkeys (key+)>
<!ELEMENT key EMPTY>
<!ATTLIST key
      Name CDATA #REQUIRED
      Function (PG_UP|PG_DOWN|DOWN|UP|ACK_FORM|NONE) #REQUIRED
>

=== DanieleSignoroni/ValvorobicaW/4.7/src/it/valvorobica/thip/logis/rf/xml/Valvorobica.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE LogisLogin SYSTEM "Lg.dtd">
<LogisLogin>
    <form Name="YpaginaCommento" Beep="alert" Type="normal" Acknowledge="lastField">
        <field Name="ESCLbl" Sequence="1" Row="1" Column="1" Width="8" Height="1" Visible="true" Value="ENTER = Avanti" SourceType="all" AcceptValueMode="enter" Mandatory="false">
            <type Display="output" Size="20" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
        </field>
         <field Name="TastoF8" Sequence="10" Row="15" Column="1" Width="8" Height="1" Visible="true" Value="F8=PG_SU" SourceType="all" AcceptValueMode="enter" Mandatory="false" RESId="paginaDestinazioneCambioUbic_TastoF8">
        <type Display="output" Size="21" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="TastoF2" Sequence="11" Row="16" Column="1" Width="9" Height="1" Visible="true" Value="F2=PG_GIU" SourceType="all" AcceptValueMode="enter" Mandatory="false" RESId="paginaDestinazioneCambioUbic_TastoF2">
        <type Display="output" Size="21" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
   <list Name="MeggaggioCommento" Header="true" Check="multiple" Row="2" Column="1" Width="21" Height="13" Visible="true">
            <item RESId="messaggioCommento">Commento</item>
        </list>
        <hotkeys>
            <key Name="F8" Function="PG_UP"/>
            <key Name="F2" Function="PG_DOWN"/>
        </hotkeys>
    </form>
     <form Name="YvisualizzaMissioneUds" Beep="none" Type="normal" Acknowledge="byFKey">
    <field Name="TastoESC" Sequence="1" Row="1" Column="1" Width="12" Height="1" Visible="true" Value="CTL_X=Missioni">
      <type Display="output" Size="12" Scale="0">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="TastoF1" Sequence="2" Row="1" Column="16" Width="5" Height="1" Visible="true" Value="F1=OK">
      <type Display="output" Size="5" Scale="0">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="TitoloLbl" Sequence="2" Row="2" Column="1" Width="15" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="15" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UMLbl" Sequence="3" Row="2" Column="16" Width="3" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="3" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UMVal" Sequence="4" Row="2" Column="19" Width="2" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="2" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="ArticoloLbl" Sequence="5" Row="3" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="CodiceArticoloVal" Sequence="6" Row="3" Column="5" Width="17" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="DescrArticoloVal" Sequence="7" Row="4" Column="1" Width="21" Height="2" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="21" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="VersioneLbl" Sequence="8" Row="5" Column="1" Width="4" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="VersioneVal" Sequence="8" Row="5" Column="5" Width="17" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="ArticoloMatricolato" Sequence="8" Row="5" Column="12" Width="10" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="10" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="Lotto1Lbl" Sequence="8" Row="6" Column="1" Width="4" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="Lotto1Val" Sequence="9" Row="6" Column="5" Width="17" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="Lotto2Lbl" Sequence="10" Row="7" Column="1" Width="4" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="Lotto2Val" Sequence="11" Row="7" Column="5" Width="17" Height="1" Visible="false" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UbicSaldoLbl" Sequence="12" Row="8" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UbicSaldoVal" Sequence="13" Row="8" Column="5" Width="17" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UdcLbl" Sequence="14" Row="9" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UdcVal" Sequence="15" Row="9" Column="5" Width="17" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UbicDestLbl" Sequence="16" Row="10" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="UbicDestVal" Sequence="17" Row="10" Column="5" Width="17" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="17" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaGiacienzaLbl" Sequence="18" Row="11" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaGiacienzaVal" Sequence="19" Row="11" Column="5" Width="6" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="6" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaDisponibileLbl" Sequence="20" Row="11" Column="12" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaDisponibileVal" Sequence="21" Row="11" Column="16" Width="6" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="6" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="BarcodeLbl" Sequence="22" Row="12" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="BarcodeTxt" Sequence="23" Row="12" Column="5" Width="60" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="input" Size="60" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaRichiestaLbl" Sequence="24" Row="13" Column="1" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaRichiestaVal" Sequence="25" Row="13" Column="5" Width="6" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="6" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
    <field Name="QtaConfermataLbl" Sequence="26" Row="13" Column="12" Width="4" Height="1" Visible="true" SourceType="all" AcceptValueMode="enter" Mandatory="false">
      <type Display="output" Size="4" Scale="0" Justify="left">com.thera.thermfw.type.StringType</type>
    </field>
