=== DanieleSignoroni/ValvorobicaW/tools/CRR2008/CRR2008PrintServer/PrintServerConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="PrintServerConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ServerConfiguration"/>
        <xs:element ref="ClientServerMapping"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ServerConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Port"/>
        <xs:element ref="RptRoot"/>
        <xs:element ref="LogPath"/>
        <xs:element ref="LogLevel"/>
        <xs:element ref="MaxLogFolders"/>        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Port" type="xs:integer"/>
  <xs:element name="RptRoot">
      <xs:simpleType>
          <xs:restriction base="xs:string">
              <xs:pattern value="[A-Za-z]:\\[^&lt;>:&quot;/\\|?\*]+(\\[^&lt;>:&quot;/\\|?\*]+)*\\?"/>
          </xs:restriction>
     </xs:simpleType>
  </xs:element> 
  <xs:element name="LogPath" type="xs:string"/>
  <xs:element name="LogLevel" type="xs:integer"/>
  <xs:element name="MaxLogFolders" type="xs:integer"/>
  <xs:element name="ClientServerMapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="CSMap"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CSMap">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ClientIp"/>
        <xs:element ref="ClientDBAlias"/>
        <xs:element ref="ServerDBAlias"/>
        <xs:element ref="ServerRptRelativePath"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ClientIp">
      <xs:simpleType>
          <xs:restriction base="xs:string">
              <xs:pattern value=" *((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]) *"/>
          </xs:restriction>
     </xs:simpleType>
  </xs:element>
  <xs:element name="ClientDBAlias" type="xs:NCName"/>  
  <xs:element name="ServerDBAlias" type="xs:NCName"/>
  <xs:element name="ServerRptRelativePath" type="xs:string"/>   
</xs:schema>

=== DanieleSignoroni/ValvorobicaW/tools/CRR2008/CRR2008PrintServer/PrintServerConfig_Template.xml
<?xml version="1.0" encoding="windows-1250"?>
<!-- Configurazione PrintServer -->
<PrintServerConfiguration xsi:noNamespaceSchemaLocation="PrintServerConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!-- Dati Generali PrintServer --> 
    <ServerConfiguration>
        <!-- Porta d'ascolto-->        
        <Port>10131</Port>
        <!-- Folder di base degli RPT su server -->
        <RptRoot>c:\Panthera</RptRoot>
        <!-- Folder di base dei logs su server -->
        <LogPath>logs</LogPath>
        <!-- Livello di log -->
        <LogLevel>logs</LogLevel>
        <!-- Massimo numero di folder di log da storicizzare -->
        <MaxLogFolders>10</MaxLogFolders>
    </ServerConfiguration>
    <!-- Mappa tra i client e il server -->
    <ClientServerMapping>      
        <!-- Client #1 -->
        <CSMap>
            <!-- IP del client -->
            <ClientIp>127.0.0.1</ClientIp>
            <!-- Database ODBC del client -->
            <ClientDBAlias>PANTH01</ClientDBAlias>
            <!-- Database ODBC del client su server -->            
            <ServerDBAlias>PANTH01</ServerDBAlias>
            <!-- Folder del server degli rpt del client (RptRoot + ...) -->
            <ServerRptRelativePath>panth01\rpt</ServerRptRelativePath>
        </CSMap>                
        <!-- Client #... -->
    </ClientServerMapping>   
</PrintServerConfiguration>

=== DanieleSignoroni/ValvorobicaW/tools/CRR2008/CRR2008PrintServer/PrintServerConfig.xml
<?xml version="1.0" encoding="windows-1250"?>
<!-- Print Server Configuration -->
<PrintServerConfiguration xsi:noNamespaceSchemaLocation="PrintServerConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">  
    <ServerConfiguration>        
        <Port>10131</Port>
        <RptRoot>W:/PthDev/Projects/Panthera/Valvorobica/4.7/rpt/cr2008</RptRoot>
        <LogPath>W:/PthDev/works/CRR2008/Valvorobica</LogPath>
        <LogLevel>0</LogLevel>
        <MaxLogFolders>10</MaxLogFolders>
    </ServerConfiguration>
    <ClientServerMapping>      
        <CSMap>
            <ClientIp>127.0.0.1</ClientIp>
            <ClientDBAlias>Valvorobica</ClientDBAlias>            
            <ServerDBAlias>Valvorobica</ServerDBAlias>
            <ServerRptRelativePath></ServerRptRelativePath>
        </CSMap>                
    </ClientServerMapping>   
</PrintServerConfiguration>
